# Generated by Django 3.0.3 on 2020-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('real_name', models.CharField(max_length=30)),
                ('real_surname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('user_class', models.IntegerField()),
            ],
        ),
    ]
