# Generated by Django 3.0.3 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200317_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('main_page_content', models.TextField()),
                ('rules', models.TextField()),
                ('number_of_problems', models.IntegerField()),
                ('constest_start', models.DateTimeField()),
                ('contest_duration_in_minutes', models.IntegerField()),
            ],
        ),
    ]
