# Generated by Django 3.0.3 on 2020-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='file_name',
            field=models.CharField(default='sol', max_length=50),
        ),
    ]
