# Generated by Django 3.0.3 on 2020-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.CharField(default='', max_length=30),
        ),
    ]
