# Generated by Django 3.0.3 on 2020-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_settings_open_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='marks_adnotation',
            field=models.CharField(default='', max_length=300),
        ),
    ]
